import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { asHomeLocale, edgeCacheKey, instagramEmbedPath, mastodonStatusPathFromAlternate, mediaSelection, parseCanonicalDecimal, resolveContainerRoute, resolveHomeLocale, validEmbedPath } from "./routes.ts";
import { internalHeader, stampGatewayHeaders } from "../worker/http.ts";
import { authorizeOffload, signatureInput } from "../worker/offload.ts";

const decimalCases = JSON.parse(await readFile(new URL("./decimal-cases.json", import.meta.url), "utf8"));
const mediaCases = JSON.parse(await readFile(new URL("./media-selection-cases.json", import.meta.url), "utf8"));
const offloadKey = Buffer.alloc(32);
const offloadKeyring = JSON.stringify({
  active: "test-v1",
  keys: { "test-v1": offloadKey.toString("base64url") },
});

function signOffload(path, expires, keyId = "test-v1", key = offloadKey) {
  return createHmac("sha256", key).update(signatureInput(keyId, path, expires)).digest("base64url");
}

test("embed accepts only supported Instagram paths", () => {
  for (const path of ["/p/Ab_12", "/reel/Ab_12", "/name/p/Ab_12", "/stories/user.name/1234567890", "/username"]) {
    assert.equal(validEmbedPath(path), true, path);
  }
  for (const path of ["https://evil.test/p/Ab_12", "//evil.test/p/Ab_12", "/\\evil.test/p/Ab_12", "/p/Ab_12?x=1", "/api/embed", "/p/!", "/p/Ab_12/01", "/p/Ab_12/+1", "/p/Ab_12/-1", "/p/Ab_12/1.5", "/p/Ab_12/1oops", "/stories/username/not-a-number", "/bad/path"]) {
    assert.equal(validEmbedPath(path), false, path);
  }
  for (const { raw, value } of decimalCases) assert.equal(parseCanonicalDecimal(raw), value, raw);
});

test("live preview preserves Instagram img_index", () => {
  const path = instagramEmbedPath(
    "https://www.instagram.com/p/Ab_12/?img_index=2&utm_source=ig_web_copy_link"
  );
  assert.equal(path, "/p/Ab_12?img_index=2");
  assert.equal(validEmbedPath(path ?? ""), true);
  assert.equal(instagramEmbedPath("https://instagram.com/%09/evil.test/p/Ab_12"), null);
});

test("Discord alternate links resolve only to same-origin Mastodon statuses", () => {
  const origin = "https://oginstagram.com";
  for (const href of [
    "/users/user.name/statuses/123",
    "https://oginstagram.com/users/user.name/statuses/123?cache=2",
  ]) {
    assert.equal(mastodonStatusPathFromAlternate(href, origin), "/api/v1/statuses/123", href);
  }
  for (const href of [
    "https://evil.test/users/user.name/statuses/123",
    "/users/user!/statuses/123",
    "/users/user.name/statuses/not-a-snowcode",
    "/users/user.name/statuses/123/extra",
    `/users/user.name/statuses/${"1".repeat(257)}`,
  ]) {
    assert.equal(mastodonStatusPathFromAlternate(href, origin), null, href);
  }
});

test("worker media cache selection follows the shared canonical cases", () => {
  for (const { query, pathIndex, selected } of mediaCases) {
    assert.equal(mediaSelection(new URLSearchParams(query), pathIndex), selected, query || `path=${pathIndex}`);
  }
});

test("worker redirects both reel aliases to the canonical reel path", () => {
  for (const path of ["/reel/Ab_12", "/reels/Ab_12", "/name/reel/Ab_12", "/name/reels/Ab_12/2"]) {
    const route = resolveContainerRoute(new URL(`https://oginstagram.com${path}`));
    assert.match(route?.humanRedirect ?? "", /^https:\/\/www\.instagram\.com\/reel\/Ab_12\//, path);
  }
});

test("offload accepts every canonical path generated by the server", () => {
  for (const path of [
    "/offload/Ab_12",
    "/offload/Ab_12/avatar",
    "/offload/Ab_12/1",
    "/offload/Ab_12/2.mp4",
    "/offload/Ab_12/50",
    "/offload/Ab_12/50.mp4",
    "/offload/story",
    "/offload/story/avatar",
    "/offload/story/1",
    "/offload/@User.Name",
    "/offload/@User.Name/avatar",
    "/offload/@User.Name/1",
    "/offload/@User.Name/6",
    "/offload/story/User.Name/123",
    "/offload/story/User.Name/123/avatar",
  ]) {
    const route = resolveContainerRoute(new URL(`https://oginstagram.com${path}`));
    assert.notEqual(route, null, path);
    const canonical = path
      .replace("/offload/@User.Name", "/offload/@user.name")
      .replace("/offload/story/User.Name/", "/offload/story/user.name/");
    assert.equal(route.cacheKey, canonical, path);
  }
});

test("offload rejects unsupported suffixes and non-canonical aliases", () => {
  for (const path of [
    "/offload",
    "/offload/!",
    "/offload/@",
    "/offload/@User.Name/1.mp4",
    "/offload/@User.Name/anything",
    "/offload/@User.Name/0",
    "/offload/Ab_12/anything",
    "/offload/Ab_12/0",
    "/offload/Ab_12/00",
    "/offload/Ab_12/01",
    "/offload/Ab_12/+1",
    "/offload/Ab_12/-1",
    "/offload/Ab_12/1.0",
    "/offload/Ab_12/0.mp4",
    "/offload/Ab_12/01.mp4",
    "/offload/Ab_12/1.MP4",
    "/offload/Ab_12/51",
    "/offload/Ab_12/51.mp4",
    "/offload/@User.Name/7",
    "/offload/@User.Name/50",
    "/offload/Ab_12/9007199254740991",
    "/offload/Ab_12/9007199254740992",
    "/offload/Ab_12/1/extra",
    "/offload/story/User.Name/not-a-number",
    "/offload/story/User!.Name/123",
    "/offload/story/User.Name/123/other",
    "/offload/story/User.Name/123/avatar/extra",
    "/offload/Ab_12/1/",
    "/offload//Ab_12/1",
    "/offload/%41b_12/1",
  ]) {
    assert.equal(resolveContainerRoute(new URL(`https://oginstagram.com${path}`)), null, path);
  }
});

test("offload cache keys include only the query parameter used by the server", () => {
  const thumbnail = resolveContainerRoute(new URL("https://oginstagram.com/offload/Ab_12/1?thumbnail=0&ignored=1"));
  const ignored = resolveContainerRoute(new URL("https://oginstagram.com/offload/Ab_12/1?ignored=1"));
  assert.deepEqual(thumbnail, {
    cacheKey: "/offload/Ab_12/1?thumbnail=1",
    offloadPath: "/offload/Ab_12/1",
  });
  assert.deepEqual(ignored, {
    cacheKey: "/offload/Ab_12/1",
    offloadPath: "/offload/Ab_12/1",
  });
});

test("offload capability matches the Go HMAC vector and shares one resource cache entry", async () => {
  assert.equal(
    signOffload("/offload/Ab_12/1", 4102444800),
    "CqgnG0rUpAoYVk7_SysTiO6WSXKBb4syu-WbZPuYDtY"
  );
  const expires = Math.floor(Date.now() / 1000) + 14 * 24 * 60 * 60 - 60;
  const signature = signOffload("/offload/Ab_12/1", expires);
  const raw = `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=${expires}&sig=${signature}`;
  const url = new URL(raw);
  const route = resolveContainerRoute(url);
  assert.notEqual(route, null);
  assert.equal(
    signatureInput("test-v1", route.offloadPath, 4102444800),
    "oginstagram-offload-capability\nv=2\nkid=test-v1\nexp=4102444800\npath=/offload/Ab_12/1\n"
  );
  assert.equal(await authorizeOffload(url, route.offloadPath, offloadKeyring), true);
  const rotated = JSON.stringify({
    active: "test-v2",
    keys: {
      "test-v1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "test-v2": Buffer.alloc(32, 1).toString("base64url"),
    },
  });
  assert.equal(await authorizeOffload(url, route.offloadPath, rotated), true);
  const signedKey = edgeCacheKey(route, url);
  assert.equal(signedKey, edgeCacheKey(route, new URL("https://oginstagram.com/offload/Ab_12/1")));

  // thumbnail and preview are representations of the same logical resource;
  // the dashboard adds them after receiving the signed media URL.
  const mutated = new URL(raw);
  mutated.searchParams.set("thumbnail", "1");
  mutated.searchParams.set("preview", "1");
  assert.equal(await authorizeOffload(mutated, route.offloadPath, offloadKeyring), true);
  const thumbnailRoute = resolveContainerRoute(mutated);
  assert.notEqual(edgeCacheKey(thumbnailRoute, mutated), signedKey);
});

test("offload capability rejects tampering, malformed input, and expiry abuse", async () => {
  const expires = Math.floor(Date.now() / 1000) + 60;
  const signature = signOffload("/offload/Ab_12/1", expires);
  const expired = Math.floor(Date.now() / 1000) - 60;
  const expiredSignature = signOffload("/offload/Ab_12/1", expired);
  const tooFar = Math.floor(Date.now() / 1000) + 14 * 24 * 60 * 60 + 60;
  const tooFarSignature = signOffload("/offload/Ab_12/1", tooFar);
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  const last = alphabet.indexOf(signature.at(-1));
  const nonCanonicalSignature = signature.slice(0, -1) + alphabet[last + 1];
  const signed = `v=2&kid=test-v1&exp=${expires}&sig=${signature}`;
  const cases = [
    `https://oginstagram.com/offload/Ab_12/2?${signed}`,
    `https://oginstagram.com/offload/ab_12/1?${signed}`,
    `https://oginstagram.com/offload/Ab_12/1?${signed}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&exp=${expires}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=missing&exp=${expires}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=1&kid=test-v1&exp=${expires}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=${expires + 1}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=0${expires}&sig=${signature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=${expired}&sig=${expiredSignature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=${tooFar}&sig=${tooFarSignature}`,
    `https://oginstagram.com/offload/Ab_12/1?v=2&kid=test-v1&exp=${expires}&sig=${nonCanonicalSignature}`,
    `https://oginstagram.com/offload/Ab_12/1?${signed}&thumbnail=0`,
    `https://oginstagram.com/offload/Ab_12/1?${signed}&preview=other`,
  ];
  for (const raw of cases) {
    const url = new URL(raw);
    const route = resolveContainerRoute(url);
    assert.notEqual(route, null, raw);
    assert.equal(await authorizeOffload(url, route.offloadPath, offloadKeyring), false, raw);
  }

  const partial = new URL("https://oginstagram.com/offload/Ab_12/1?sig=broken");
  const partialRoute = resolveContainerRoute(partial);
  assert.equal(await authorizeOffload(partial, partialRoute.offloadPath, offloadKeyring), false);

  const unsigned = new URL("https://oginstagram.com/offload/Ab_12/1");
  const unsignedRoute = resolveContainerRoute(unsigned);
  assert.equal(await authorizeOffload(unsigned, unsignedRoute.offloadPath, undefined), false);

  const valid = new URL(`https://oginstagram.com/offload/Ab_12/1?${signed}`);
  const validRoute = resolveContainerRoute(valid);
  await assert.rejects(
    authorizeOffload(valid, validRoute.offloadPath, JSON.stringify({
      active: "test-v1",
      keys: { "test-v1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
      extra: true,
    })),
    /invalid keyring/
  );
  await assert.rejects(
    authorizeOffload(valid, validRoute.offloadPath, JSON.stringify({
      active: "test-v1",
      keys: { "test-v1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB" },
    })),
    /base64url-encoded 32-byte/
  );
});

test("gateway strips client authorization headers and stamps only verified capability state", () => {
  const request = new Request("https://oginstagram.com/offload/Ab_12/1", {
    headers: {
      [internalHeader.allowOriginFetch]: "1",
      [internalHeader.signedOffload]: "1",
    },
  });
  const plain = stampGatewayHeaders(request, new URL(request.url), "request-1");
  assert.equal(plain.headers.get(internalHeader.allowOriginFetch), null);
  assert.equal(plain.headers.get(internalHeader.signedOffload), null);

  const signed = stampGatewayHeaders(request, new URL(request.url), "request-2", {
    signedOffload: true,
  });
  assert.equal(signed.headers.get(internalHeader.allowOriginFetch), null);
  assert.equal(signed.headers.get(internalHeader.signedOffload), "1");

  const httpUrl = new URL("http://www.oginstagram.com/p/Ab_12");
  const secure = stampGatewayHeaders(new Request(httpUrl), httpUrl, "request-3");
  assert.equal(secure.headers.get(internalHeader.publicOrigin), "https://www.oginstagram.com");
});

test("case-insensitive offload subjects share one edge cache key", () => {
  const profileUpper = resolveContainerRoute(new URL("https://oginstagram.com/offload/@User.Name/avatar"));
  const profileLower = resolveContainerRoute(new URL("https://oginstagram.com/offload/@user.name/avatar"));
  const storyUpper = resolveContainerRoute(new URL("https://oginstagram.com/offload/story/User.Name/123"));
  const storyLower = resolveContainerRoute(new URL("https://oginstagram.com/offload/story/user.name/123"));
  assert.equal(profileUpper.cacheKey, profileLower.cacheKey);
  assert.equal(storyUpper.cacheKey, storyLower.cacheKey);
});

test("case-insensitive story routes share one edge cache key", () => {
  for (const host of ["oginstagram.com", "g.oginstagram.com", "d.oginstagram.com"]) {
    const upperUrl = new URL(`https://${host}/stories/User.Name/123`);
    const lowerUrl = new URL(`https://${host}/stories/user.name/123`);
    const upper = resolveContainerRoute(upperUrl);
    const lower = resolveContainerRoute(lowerUrl);
    assert.notEqual(upper, null);
    assert.notEqual(lower, null);
    assert.equal(edgeCacheKey(upper, upperUrl), edgeCacheKey(lower, lowerUrl), host);
  }
  const direct = resolveContainerRoute(new URL("https://d.oginstagram.com/stories/User.Name/123"));
  assert.equal(direct.rewritePath, "/offload/story/user.name/123");
});

test("only direct post and story rewrites authorize a first-time offload fetch", () => {
  for (const path of ["/p/Ab_12", "/stories/User.Name/123"]) {
    const route = resolveContainerRoute(new URL(`https://d.oginstagram.com${path}`));
    assert.notEqual(route, null, path);
    assert.equal(route.allowOffloadFetch, true, path);
    assert.match(route.rewritePath, /^\/offload\//, path);
  }

  for (const url of [
    "https://oginstagram.com/offload/Ab_12/1",
    "https://oginstagram.com/p/Ab_12",
    "https://g.oginstagram.com/p/Ab_12",
    "https://d.oginstagram.com/User.Name",
  ]) {
    const route = resolveContainerRoute(new URL(url));
    assert.notEqual(route, null, url);
    assert.equal(route.allowOffloadFetch, undefined, url);
  }
});

test("edge cache key separates every public hostname", () => {
  const hosts = ["oginstagram.com", "www.oginstagram.com", "d.oginstagram.com", "g.oginstagram.com"];
  const keysBySite = new Map();
  for (const host of hosts) {
    const url = new URL(`https://${host}/p/Ab_12/`);
    const route = resolveContainerRoute(url);
    assert.notEqual(route, null, host);
    const key = edgeCacheKey(route, url);
    keysBySite.set(key, host);
  }
  assert.equal(keysBySite.size, 4);
  const plain = resolveContainerRoute(new URL("https://oginstagram.com/p/Ab_12/"));
  const www = resolveContainerRoute(new URL("https://www.oginstagram.com/p/Ab_12/"));
  assert.notEqual(
    edgeCacheKey(plain, new URL("https://oginstagram.com/p/Ab_12/")),
    edgeCacheKey(www, new URL("https://www.oginstagram.com/p/Ab_12/"))
  );
});

test("public __gallery input is stripped and cannot change a plain-host response", () => {
  const plain = new URL("https://oginstagram.com/p/Ab_12");
  const poisoned = new URL("https://oginstagram.com/p/Ab_12?__gallery=1");
  const plainRoute = resolveContainerRoute(plain);
  const poisonedRoute = resolveContainerRoute(poisoned);
  assert.notEqual(plainRoute, null);
  assert.notEqual(poisonedRoute, null);
  assert.equal(poisonedRoute.rewritePath, "/p/Ab_12");
  assert.equal(poisonedRoute.cacheKey, plainRoute.cacheKey);

  const gallery = resolveContainerRoute(new URL("https://g.oginstagram.com/p/Ab_12?__gallery=0"));
  assert.notEqual(gallery, null);
  assert.equal(gallery.rewritePath, "/p/Ab_12?__gallery=1");
  assert.notEqual(gallery.cacheKey, plainRoute.cacheKey);
});

test("host modes require an exact service hostname", () => {
  const attacker = new URL("https://d.evil.test/p/Ab_12");
  const route = resolveContainerRoute(attacker);
  assert.notEqual(route, null);
  assert.equal(route.rewritePath, undefined);
  assert.match(route.cacheKey, /^\/embed\//);
});

test("profile cache keys canonicalize username case without a bot variant", () => {
  const upperUrl = new URL("https://oginstagram.com/User.Name");
  const lowerUrl = new URL("https://oginstagram.com/user.name");
  const upper = resolveContainerRoute(upperUrl);
  const lower = resolveContainerRoute(lowerUrl);
  assert.notEqual(upper, null);
  assert.notEqual(lower, null);
  assert.equal(upper.cacheKey, lower.cacheKey);
});

test("home locale negotiation", () => {
  const cases = [
    ["ko-KR,ko;q=0.9,en-US;q=0.8", "ko"],
    ["zh-TW", "zh-hant"],
    ["zh-Hant-HK", "zh-hant"],
    ["zh-HK", "zh-hant"],
    ["zh-MO", "zh-hant"],
    ["zh-CN", "zh-hans"],
    ["zh-Hans-SG", "zh-hans"],
    ["zh", "zh-hans"],
    ["pt-BR,pt;q=0.9", "pt"],
    ["fr-FR,fr;q=0.9", "fr"],
    ["es-419", "es"],
    ["en;q=0, ko;q=1", "ko"],
    ["fr;q=0.2, ja;q=0.8", "ja"],
    ["ko;q=0, *;q=1", "en"],
    ["ko;q=bogus, en;q=0.5", "en"],
    ["de-DE,it;q=0.8", "en"],
    ["", "en"],
  ];
  for (const [accept, want] of cases) {
    assert.equal(resolveHomeLocale(accept), want, accept);
  }
  assert.equal(asHomeLocale("zh-hant"), "zh-hant");
  assert.equal(asHomeLocale("nope"), null);
});
